CFLAGS += -std=c11 -msse4.2 -Isrc -include src/hfsinspect-Prefix.pch
CFLAGS += -g -O0 -Wall

SOURCEDIRS := src src/crc32c src/hfs src/hfs/Apple src/hfs/btree src/hfs/hfsplus src/logging src/misc src/volumes
SOURCES := $(foreach dir,$(SOURCEDIRS),$(wildcard $(dir)/*.c))
OBJECTS = $(SOURCES:.c=.o)

.PHONY: all
all: hfsinspect

hfsinspect: $(OBJECTS)
	$(LINK.c) -o "$(BINDIR)/$@" $^ $(LIBS)

.PHONY: clean
clean: $(BINDIR)
	$(RM) "$(BINDIR)/*" $(OBJECTS)
	
